[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  PAYLOAD_SECRET = "development-secret-key-for-local-testing"
  DATABASE_URI = "postgresql://postgres.awtneocokxlaunyxajzr:Codingclubcuh%4022@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres"
  NEXT_PUBLIC_SERVER_URL = "https://codingclubcuh.online"
  CLOUDINARY_CLOUD_NAME = "azzisskq"
  CLOUDINARY_UPLOAD_PRESET = "codingclubuploads"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "azzisskq"
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET = "codingclubuploads"

[context.production.environment]
  PAYLOAD_SECRET = "development-secret-key-for-local-testing"
  DATABASE_URI = "postgresql://postgres.awtneocokxlaunyxajzr:Codingclubcuh%4022@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres"
  NEXT_PUBLIC_SERVER_URL = "https://codingclubcuh.online"
  CLOUDINARY_CLOUD_NAME = "azzisskq"
  CLOUDINARY_UPLOAD_PRESET = "codingclubuploads"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME = "azzisskq"
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET = "codingclubuploads"

[[plugins]]
  package = "@netlify/plugin-nextjs"
